---
kind: pipeline
name: build

clone:
  depth: 50

steps:
  #- name: golint
   # image: golangci/golangci-lint:v1.31.0
    #pull: true
    #commands:
     # - golangci-lint run --out-format=json --issues-exit-code=0 -v

  - name: hadolint
    image: hadolint/hadolint:latest
    commands:
      - hadolint Dockerfile

  - name: publish
    image: plugins/docker
    settings:
      repo: lukasbahr/prometheus-bme280-exporter
      tags: "${DRONE_COMMIT_SHA:0:7}"
      # auto_tag: true
      #auto_tag_suffix: linux-amd64
      dockerfile: Dockerfile
      build_args:
        - VERSION=${DRONE_COMMIT_SHA:0:7}
      username:
        from_secret: REGISTRY_USERNAME
      password:
        from_secret: REGISTRY_PASSWORD
    when:
      event:
        - push
        - tag