version: "3.7"

services:

  exporter:
    image: ghcr.io/lukibahr/Prometheus-BME280-exporter:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9123:9123
    container_name: exporter
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9123/health"]
      interval: 5s
      timeout: 10s
      retries: 5      