version: "3.7"

services:

  exporter:
    image:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9123:9123
    container_name: exporter
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5